### ISSUE TITLE
Bar release file

### ISSUE THREAD

**Issue by vaskas** [infsega/boswars-playbook#1]
Hi Sergey,
Do you happen to have the bar file for BosWars? I would love to give it a go on my BB10 phones! Your fheroes2 port still works great. If not I am happy to compile it.

**Comment by infsega** [comment]
Hello!

Sorry, the porting was not completed.

пт, 14 мая 2021 г., 17:46 vaskas ***@***.***>:

**Comment by vaskas** [comment]
I see, thank you for the quick response!
